In [1]:
import sys
import pandas as pd
sys.path.append('../../')

from src.data.preprocessing import apply_lowering, apply_remove_extra_quotations

In [5]:

df = pd.read_csv("../../data/interim/interim_internship_challenge - dataset.csv")
df.head(3)

,id,text,label
0,5b133284a6da98dccdde5f03,""" High quality and perfection are the result o...",0
1,556d34fd7369641226dab000,"""BEST HAM IN THE WORLD""​- IFFA International F...",0
2,5e57ea61d5bd4a000176bd7c,"""El mundo necesita gente como La Aguacatera, q...",0

### 3.1 lower all text

In [3]:
new = apply_lowering(df)
new

,id,text,label
0,5b133284a6da98dccdde5f03,high quality and perfection are the result of...,0
1,556d34fd7369641226dab000,best ham in the world​- iffa international fra...,0
2,5e57ea61d5bd4a000176bd7c,"el mundo necesita gente como la aguacatera, qu...",0
3,5e581dba9064ba0001ceb925,el valor del trabajo bien hecho​somos un grupo...,0
4,5e55a840831f070001de01d2,fabricación y distribución de complementos ali...,1
...,...,...,...
2826,5a9cf7f2a6da98d97e72e434,"𝗧𝗨𝗥𝗢𝗠𝗔𝗦 𝘀𝗶𝗻𝗰𝗲 1985, 𝘄𝗼𝗿𝗹𝗱𝘄𝗶𝗱𝗲 𝗿𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗶𝗻 𝘁𝗵𝗲...",0
2827,5eda358292a7d400014cdbb9,𝙄𝘾𝙂 𝙂𝙧𝙤𝙪𝙥 es un grupo multinacional que fabric...,0
2828,614168ce66c01d0001074e07,cómo te ayudamos pasos definición de la cabin...,0
2829,54a1205e69702d84c5183602,what do we do?we develop saas solutions to mo...,0
2830,5da4df7af22f0400010d034c,ambar lab is your one-stop clinical laborator...,0

### 3.2 remove extra quotations and \n

In [4]:
new = apply_remove_extra_quotations(new)
new

,id,text,label
0,5b133284a6da98dccdde5f03,high quality and perfection are the result of...,0
1,556d34fd7369641226dab000,best ham in the world​- iffa international fra...,0
2,5e57ea61d5bd4a000176bd7c,"el mundo necesita gente como la aguacatera, qu...",0
3,5e581dba9064ba0001ceb925,el valor del trabajo bien hecho​somos un grupo...,0
4,5e55a840831f070001de01d2,fabricación y distribución de complementos ali...,1
...,...,...,...
2826,5a9cf7f2a6da98d97e72e434,"𝗧𝗨𝗥𝗢𝗠𝗔𝗦 𝘀𝗶𝗻𝗰𝗲 1985, 𝘄𝗼𝗿𝗹𝗱𝘄𝗶𝗱𝗲 𝗿𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗶𝗻 𝘁𝗵𝗲...",0
2827,5eda358292a7d400014cdbb9,𝙄𝘾𝙂 𝙂𝙧𝙤𝙪𝙥 es un grupo multinacional que fabric...,0
2828,614168ce66c01d0001074e07,cómo te ayudamos pasos definición de la cabin...,0
2829,54a1205e69702d84c5183602,what do we do?we develop saas solutions to mo...,0
2830,5da4df7af22f0400010d034c,ambar lab is your one-stop clinical laborator...,0