### 1 Read data

In [1]:
import pandas as pd

df = pd.read_csv("../../data/raw/internship_challenge - dataset.csv")
df.head()

,id,nif_code,web_site,linkedin_url,about,Label,website_url,blog_url,angellist_url,twitter_url,...,keywords,num_suborganizations,short_description,specialities_x,location_x,specialities_y,location_y,specialities,name,location
0,5b133284a6da98dccdde5f03,B53876694,palomabarcelo.com,http://www.linkedin.com/company/palomabarcelo,""" High quality and perfection are the result o...",0,http://www.palomabarcelo.com,NaN,NaN,NaN,...,"['diseno', 'calzado', 'moda', 'lujo']",0,""" High quality and perfection are the result o...","Diseño, Calzado, Moda, and Lujo","Elche, Alicante",NaN,NaN,NaN,Paloma Barcelo,NaN
1,556d34fd7369641226dab000,B37020187,beher.com,http://www.linkedin.com/company/beher-switzerland,"""BEST HAM IN THE WORLD""​- IFFA International F...",0,http://www.beher.com,NaN,NaN,NaN,...,"['acornfed ham', 'jamon iberico de bellota', '...",0,"""BEST HAM IN THE WORLD""- IFFA International Fr...","Jamón Ibérico de Bellota, Productos Ibéricos, ...","Guijuelo, Salamanca",NaN,NaN,NaN,BEHER™,NaN
2,5e57ea61d5bd4a000176bd7c,B93643716,aguacateradelsur.com,http://www.linkedin.com/company/aguacatera,"""El mundo necesita gente como La Aguacatera, q...",0,http://www.aguacateradelsur.com,NaN,NaN,NaN,...,['avocados'],0,"""El mundo necesita gente como La Aguacatera, q...",Avocados,"Vélez-Málaga, Andalucía",NaN,NaN,NaN,Compañía Aguacatera del Sur,NaN
3,5e581dba9064ba0001ceb925,A48980122,altegui.com,http://www.linkedin.com/company/dux-inversores,"""El valor del trabajo bien hecho""​\n\nSomos un...",0,http://www.duxinversores.com,NaN,NaN,NaN,...,"['asset management', 'ciclo economico y sector...",0,"""El valor del trabajo bien hecho""\n\nSomos un ...","Asset Management, Ciclo Económico y Sectores, ...","Madrid, Comunidad de Madrid",NaN,NaN,NaN,DUX INVERSORES,NaN
4,5e55a840831f070001de01d2,B74215559,siliciumg5.com,http://www.linkedin.com/company/siliciumlab,"""Fabricación y distribución de complementos al...",1,http://www.siliciumg5.com,NaN,NaN,https://twitter.com/SiliciumEspagne,...,"['rosa mosqueta', 'g7 defender', 'silicium g5'...",0,"""Fabricación y distribución de complementos al...",NaN,NaN,NaN,NaN,"Silicio Orgánico , silicium, Silica, silicium ...",SILICIUM ESPAÑA LABORATORIOS SL,"Reus, Cataluña / Catalunya"

### 1.2 check amount of N/A data

we can see that we have 2912 entries, so for each column, if we have a number lower than 2912, we need to decide
how to handle these N/A values

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2912 entries, 0 to 2911
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    2912 non-null   object
 1   nif_code              2912 non-null   object
 2   web_site              2912 non-null   object
 3   linkedin_url          2912 non-null   object
 4   about                 2912 non-null   object
 5   Label                 2912 non-null   int64
 6   website_url           2908 non-null   object
 7   blog_url              0 non-null      float64
 8   angellist_url         21 non-null     object
 9   twitter_url           1006 non-null   object
 10  facebook_url          1263 non-null   object
 11  primary_phone         2912 non-null   object
 12  languages             2912 non-null   object
 13  alexa_ranking         268 non-null    float64
 14  phone                 2181 non-null   object
 15  linkedin_uid          2867 non-null   float64
 16  primary_domain        2908 non-null   object
 17  persona_counts        2912 non-null   object
 18  keywords              2912 non-null   object
 19  num_suborganizations  2912 non-null   int64
 20  short_description     2883 non-null   object
 21  specialities_x        1842 non-null   object
 22  location_x            2339 non-null   object
 23  specialities_y        80 non-null     object
 24  location_y            96 non-null     object
 25  specialities          165 non-null    object
 26  name                  2912 non-null   object
 27  location              197 non-null    object
dtypes: float64(3), int64(2), object(23)
memory usage: 637.1+ KB

### 1.3 Explore relevant columns

We can see that **about** and **short_description** are identical, however there are fewer valid entries for **short_description**.
We don't want to repeat the same text for each company, so no need to keep **short_description**.

In [3]:
df['about']

0       " High quality and perfection are the result o...
1       "BEST HAM IN THE WORLD"​- IFFA International F...
2       "El mundo necesita gente como La Aguacatera, q...
3       "El valor del trabajo bien hecho"​\n\nSomos un...
4       "Fabricación y distribución de complementos al...
                              ...
2907    𝗧𝗨𝗥𝗢𝗠𝗔𝗦 𝘀𝗶𝗻𝗰𝗲 1985, 𝘄𝗼𝗿𝗹𝗱𝘄𝗶𝗱𝗲 𝗿𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗶𝗻 𝘁𝗵𝗲...
2908    𝙄𝘾𝙂 𝙂𝙧𝙤𝙪𝙥 es un grupo multinacional que fabric...
2909    📌 CÓMO TE AYUDAMOS\n\n◼ PASOS\n◽ Definición de...
2910    🔴 What do we do?\nWe develop SaaS solutions to...
2911    🧪 Ambar Lab is your one-stop clinical laborato...
Name: about, Length: 2912, dtype: object

In [4]:
df['short_description']

0       " High quality and perfection are the result o...
1       "BEST HAM IN THE WORLD"- IFFA International Fr...
2       "El mundo necesita gente como La Aguacatera, q...
3       "El valor del trabajo bien hecho"\n\nSomos un ...
4       "Fabricación y distribución de complementos al...
                              ...
2907    𝗧𝗨𝗥𝗢𝗠𝗔𝗦 𝘀𝗶𝗻𝗰𝗲 1985, 𝘄𝗼𝗿𝗹𝗱𝘄𝗶𝗱𝗲 𝗿𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗶𝗻 𝘁𝗵𝗲...
2908    𝙄𝘾𝙂 𝙂𝙧𝙤𝙪𝙥 es un grupo multinacional que fabric...
2909    📌 CÓMO TE AYUDAMOS\n\n◼ PASOS\n◽ Definición de...
2910    🔴 What do we do?\nWe develop SaaS solutions to...
2911    🧪 Ambar Lab is your one-stop clinical laborato...
Name: short_description, Length: 2912, dtype: object

We can see that **specialities_x** is more descriptive and numerous than
**specialities_y** and **specialities**, so we will keep **specialities_x**.
In order to deal with NaN values, we can replace it with empty strings.

In [5]:
df['specialities_x']

0                         Diseño, Calzado, Moda, and Lujo
1       Jamón Ibérico de Bellota, Productos Ibéricos, ...
2                                                Avocados
3       Asset Management, Ciclo Económico y Sectores, ...
4                                                     NaN
                              ...
2907    Taylor made solutions and projects, Proyectos ...
2908                                                  NaN
2909                                                  NaN
2910    Last mile , Delivery, Technology, Logistics, a...
2911    Reference laboratory, Clinical laboratory, Dia...
Name: specialities_x, Length: 2912, dtype: object

In [6]:
print(df['specialities_y'].count())
print(df['specialities'].count())

80
165

**keywords** is also very relevant

In [7]:
df['keywords']

0                   ['diseno', 'calzado', 'moda', 'lujo']
1       ['acornfed ham', 'jamon iberico de bellota', '...
2                                            ['avocados']
3       ['asset management', 'ciclo economico y sector...
4       ['rosa mosqueta', 'g7 defender', 'silicium g5'...
                              ...
2907    ['glass', 'maquinaria industrial', 'vidrio', '...
2908                                                   []
2909                                                   []
2910    ['e-commerce', 'software', 'transportation', '...
2911    ['reference laboratory', 'projects acceleratio...
Name: keywords, Length: 2912, dtype: object

### 1.4 create new df with desired columns

In [8]:
new_df = df[['id', 'about', 'keywords', 'specialities_x', 'Label']]
new_df

,id,about,keywords,specialities_x,Label
0,5b133284a6da98dccdde5f03,""" High quality and perfection are the result o...","['diseno', 'calzado', 'moda', 'lujo']","Diseño, Calzado, Moda, and Lujo",0
1,556d34fd7369641226dab000,"""BEST HAM IN THE WORLD""​- IFFA International F...","['acornfed ham', 'jamon iberico de bellota', '...","Jamón Ibérico de Bellota, Productos Ibéricos, ...",0
2,5e57ea61d5bd4a000176bd7c,"""El mundo necesita gente como La Aguacatera, q...",['avocados'],Avocados,0
3,5e581dba9064ba0001ceb925,"""El valor del trabajo bien hecho""​\n\nSomos un...","['asset management', 'ciclo economico y sector...","Asset Management, Ciclo Económico y Sectores, ...",0
4,5e55a840831f070001de01d2,"""Fabricación y distribución de complementos al...","['rosa mosqueta', 'g7 defender', 'silicium g5'...",NaN,1
...,...,...,...,...,...
2907,5a9cf7f2a6da98d97e72e434,"𝗧𝗨𝗥𝗢𝗠𝗔𝗦 𝘀𝗶𝗻𝗰𝗲 1985, 𝘄𝗼𝗿𝗹𝗱𝘄𝗶𝗱𝗲 𝗿𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗶𝗻 𝘁𝗵𝗲...","['glass', 'maquinaria industrial', 'vidrio', '...","Taylor made solutions and projects, Proyectos ...",0
2908,5eda358292a7d400014cdbb9,𝙄𝘾𝙂 𝙂𝙧𝙤𝙪𝙥 es un grupo multinacional que fabric...,[],NaN,0
2909,614168ce66c01d0001074e07,📌 CÓMO TE AYUDAMOS\n\n◼ PASOS\n◽ Definición de...,[],NaN,0
2910,54a1205e69702d84c5183602,🔴 What do we do?\nWe develop SaaS solutions to...,"['e-commerce', 'software', 'transportation', '...","Last mile , Delivery, Technology, Logistics, a...",0
2911,5da4df7af22f0400010d034c,🧪 Ambar Lab is your one-stop clinical laborato...,"['reference laboratory', 'projects acceleratio...","Reference laboratory, Clinical laboratory, Dia...",0

### 1.5 replace NaN with an empty string in **specialities_x**

In [9]:
new_df['specialities_x'] =  new_df['specialities_x'].fillna('')
new_df

/tmp/ipykernel_40392/2868050330.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['specialities_x'] =  new_df['specialities_x'].fillna('')

,id,about,keywords,specialities_x,Label
0,5b133284a6da98dccdde5f03,""" High quality and perfection are the result o...","['diseno', 'calzado', 'moda', 'lujo']","Diseño, Calzado, Moda, and Lujo",0
1,556d34fd7369641226dab000,"""BEST HAM IN THE WORLD""​- IFFA International F...","['acornfed ham', 'jamon iberico de bellota', '...","Jamón Ibérico de Bellota, Productos Ibéricos, ...",0
2,5e57ea61d5bd4a000176bd7c,"""El mundo necesita gente como La Aguacatera, q...",['avocados'],Avocados,0
3,5e581dba9064ba0001ceb925,"""El valor del trabajo bien hecho""​\n\nSomos un...","['asset management', 'ciclo economico y sector...","Asset Management, Ciclo Económico y Sectores, ...",0
4,5e55a840831f070001de01d2,"""Fabricación y distribución de complementos al...","['rosa mosqueta', 'g7 defender', 'silicium g5'...",,1
...,...,...,...,...,...
2907,5a9cf7f2a6da98d97e72e434,"𝗧𝗨𝗥𝗢𝗠𝗔𝗦 𝘀𝗶𝗻𝗰𝗲 1985, 𝘄𝗼𝗿𝗹𝗱𝘄𝗶𝗱𝗲 𝗿𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗶𝗻 𝘁𝗵𝗲...","['glass', 'maquinaria industrial', 'vidrio', '...","Taylor made solutions and projects, Proyectos ...",0
2908,5eda358292a7d400014cdbb9,𝙄𝘾𝙂 𝙂𝙧𝙤𝙪𝙥 es un grupo multinacional que fabric...,[],,0
2909,614168ce66c01d0001074e07,📌 CÓMO TE AYUDAMOS\n\n◼ PASOS\n◽ Definición de...,[],,0
2910,54a1205e69702d84c5183602,🔴 What do we do?\nWe develop SaaS solutions to...,"['e-commerce', 'software', 'transportation', '...","Last mile , Delivery, Technology, Logistics, a...",0
2911,5da4df7af22f0400010d034c,🧪 Ambar Lab is your one-stop clinical laborato...,"['reference laboratory', 'projects acceleratio...","Reference laboratory, Clinical laboratory, Dia...",0

### 1.6 remove emojis from **about** and also :smiley_face: which remains after removing emojis

In [10]:
import emoji
import re


def remove_emojis(text: str)-> str:
    """ removes emojis and :emoji: syntax from text.
    """
    text_no_emojis = emoji.demojize(text)
    cleaned_text = re.sub(r':[^:]+:', '', text_no_emojis)
    return cleaned_text


new_df['about'] = df['about'].apply(remove_emojis)
new_df

/tmp/ipykernel_40392/863998829.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['about'] = df['about'].apply(remove_emojis)

,id,about,keywords,specialities_x,Label
0,5b133284a6da98dccdde5f03,""" High quality and perfection are the result o...","['diseno', 'calzado', 'moda', 'lujo']","Diseño, Calzado, Moda, and Lujo",0
1,556d34fd7369641226dab000,"""BEST HAM IN THE WORLD""​- IFFA International F...","['acornfed ham', 'jamon iberico de bellota', '...","Jamón Ibérico de Bellota, Productos Ibéricos, ...",0
2,5e57ea61d5bd4a000176bd7c,"""El mundo necesita gente como La Aguacatera, q...",['avocados'],Avocados,0
3,5e581dba9064ba0001ceb925,"""El valor del trabajo bien hecho""​\n\nSomos un...","['asset management', 'ciclo economico y sector...","Asset Management, Ciclo Económico y Sectores, ...",0
4,5e55a840831f070001de01d2,"""Fabricación y distribución de complementos al...","['rosa mosqueta', 'g7 defender', 'silicium g5'...",,1
...,...,...,...,...,...
2907,5a9cf7f2a6da98d97e72e434,"𝗧𝗨𝗥𝗢𝗠𝗔𝗦 𝘀𝗶𝗻𝗰𝗲 1985, 𝘄𝗼𝗿𝗹𝗱𝘄𝗶𝗱𝗲 𝗿𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗶𝗻 𝘁𝗵𝗲...","['glass', 'maquinaria industrial', 'vidrio', '...","Taylor made solutions and projects, Proyectos ...",0
2908,5eda358292a7d400014cdbb9,𝙄𝘾𝙂 𝙂𝙧𝙤𝙪𝙥 es un grupo multinacional que fabric...,[],,0
2909,614168ce66c01d0001074e07,CÓMO TE AYUDAMOS\n\n PASOS\n Definición de la...,[],,0
2910,54a1205e69702d84c5183602,What do we do?\nWe develop SaaS solutions to ...,"['e-commerce', 'software', 'transportation', '...","Last mile , Delivery, Technology, Logistics, a...",0
2911,5da4df7af22f0400010d034c,Ambar Lab is your one-stop clinical laborator...,"['reference laboratory', 'projects acceleratio...","Reference laboratory, Clinical laboratory, Dia...",0

### 1.7 Lower all text to keep our data uniform.

In [11]:
# columns_to_lower = ['about', 'keywords', 'specialities_x']
# new_df[columns_to_lower] = new_df[columns_to_lower].apply(lambda x: x.astype(str).str.lower())
# new_df

### 1.8 remove extra quotation marks within **about**
There are too many uses of quotations withing 'about' that we should remove for clarity.

In [12]:
# def remove_extra_quotations(text:str)-> str:
#     """ removes extra quotation marks found within text.
#     """
#     alist = text.split('"')
#     return ''.join(alist)


# new_df['about'] = new_df['about'].apply(remove_extra_quotations)
# new_df

### 1.9 **specialities_x** **keywords** are acutally strings that look like lists. They need to be converted to lists.

In [13]:
from typing import List 


def convert_to_list(text:str)-> List[str]:
    """ Removal of unwanted words and characters from strings.
    Finally, conversion to a list.
    """
    cleaned = text.replace('and', '').replace("[", '').replace("]", '').replace("'", '').split(',')
    return cleaned


target_columns = ['specialities_x', 'keywords']
new_df[target_columns] = new_df[target_columns].applymap(convert_to_list)

new_df

/tmp/ipykernel_40392/2979460899.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  new_df[target_columns] = new_df[target_columns].applymap(convert_to_list)
/tmp/ipykernel_40392/2979460899.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df[target_columns] = new_df[target_columns].applymap(convert_to_list)

,id,about,keywords,specialities_x,Label
0,5b133284a6da98dccdde5f03,""" High quality and perfection are the result o...","[diseno, calzado, moda, lujo]","[Diseño, Calzado, Moda, Lujo]",0
1,556d34fd7369641226dab000,"""BEST HAM IN THE WORLD""​- IFFA International F...","[acornfed ham, jamon iberico de bellota, pro...","[Jamón Ibérico de Bellota, Productos Ibéricos...",0
2,5e57ea61d5bd4a000176bd7c,"""El mundo necesita gente como La Aguacatera, q...",[avocados],[Avocados],0
3,5e581dba9064ba0001ceb925,"""El valor del trabajo bien hecho""​\n\nSomos un...","[asset management, ciclo economico y sectores...","[Asset Management, Ciclo Económico y Sectores...",0
4,5e55a840831f070001de01d2,"""Fabricación y distribución de complementos al...","[rosa mosqueta, g7 defender, silicium g5, s...",[],1
...,...,...,...,...,...
2907,5a9cf7f2a6da98d97e72e434,"𝗧𝗨𝗥𝗢𝗠𝗔𝗦 𝘀𝗶𝗻𝗰𝗲 1985, 𝘄𝗼𝗿𝗹𝗱𝘄𝗶𝗱𝗲 𝗿𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗶𝗻 𝘁𝗵𝗲...","[glass, maquinaria industrial, vidrio, proy...","[Taylor made solutions projects, Proyectos y...",0
2908,5eda358292a7d400014cdbb9,𝙄𝘾𝙂 𝙂𝙧𝙤𝙪𝙥 es un grupo multinacional que fabric...,[],[],0
2909,614168ce66c01d0001074e07,CÓMO TE AYUDAMOS\n\n PASOS\n Definición de la...,[],[],0
2910,54a1205e69702d84c5183602,What do we do?\nWe develop SaaS solutions to ...,"[e-commerce, software, transportation, mobi...","[Last mile , Delivery, Technology, Logistic...",0
2911,5da4df7af22f0400010d034c,Ambar Lab is your one-stop clinical laborator...,"[reference laboratory, projects acceleration,...","[Reference laboratory, Clinical laboratory, ...",0

### 1.10 Creating a new column as the set of **keywords** and **specialities_x**

In [14]:
new_df['merged'] = new_df.apply(lambda row: list(set(row['keywords'] + row['specialities_x'])), axis=1)
new_df

/tmp/ipykernel_40392/1738694512.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['merged'] = new_df.apply(lambda row: list(set(row['keywords'] + row['specialities_x'])), axis=1)

,id,about,keywords,specialities_x,Label,merged
0,5b133284a6da98dccdde5f03,""" High quality and perfection are the result o...","[diseno, calzado, moda, lujo]","[Diseño, Calzado, Moda, Lujo]",0,"[ Lujo, Calzado, diseno, Diseño, lujo, Mod..."
1,556d34fd7369641226dab000,"""BEST HAM IN THE WORLD""​- IFFA International F...","[acornfed ham, jamon iberico de bellota, pro...","[Jamón Ibérico de Bellota, Productos Ibéricos...",0,"[ Best ham of the world, best ham of the wor..."
2,5e57ea61d5bd4a000176bd7c,"""El mundo necesita gente como La Aguacatera, q...",[avocados],[Avocados],0,"[Avocados, avocados]"
3,5e581dba9064ba0001ceb925,"""El valor del trabajo bien hecho""​\n\nSomos un...","[asset management, ciclo economico y sectores...","[Asset Management, Ciclo Económico y Sectores...",0,"[Asset Management, analisis fundamental, Ges..."
4,5e55a840831f070001de01d2,"""Fabricación y distribución de complementos al...","[rosa mosqueta, g7 defender, silicium g5, s...",[],1,"[, neuro health, silicium g7 silicium, sili..."
...,...,...,...,...,...,...
2907,5a9cf7f2a6da98d97e72e434,"𝗧𝗨𝗥𝗢𝗠𝗔𝗦 𝘀𝗶𝗻𝗰𝗲 1985, 𝘄𝗼𝗿𝗹𝗱𝘄𝗶𝗱𝗲 𝗿𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗶𝗻 𝘁𝗵𝗲...","[glass, maquinaria industrial, vidrio, proy...","[Taylor made solutions projects, Proyectos y...",0,"[Taylor made solutions projects, smart glass..."
2908,5eda358292a7d400014cdbb9,𝙄𝘾𝙂 𝙂𝙧𝙤𝙪𝙥 es un grupo multinacional que fabric...,[],[],0,[]
2909,614168ce66c01d0001074e07,CÓMO TE AYUDAMOS\n\n PASOS\n Definición de la...,[],[],0,[]
2910,54a1205e69702d84c5183602,What do we do?\nWe develop SaaS solutions to ...,"[e-commerce, software, transportation, mobi...","[Last mile , Delivery, Technology, Logistic...",0,"[ napalo, internet, e-commerce, ondemdeliver..."
2911,5da4df7af22f0400010d034c,Ambar Lab is your one-stop clinical laborator...,"[reference laboratory, projects acceleration,...","[Reference laboratory, Clinical laboratory, ...",0,"[ clinical laboratory, Projects acceleration..."

### 1.11 Dropping unnecessary columns

In [15]:
columns_to_drop = ['keywords', 'specialities_x']
new_df.drop(columns=columns_to_drop, inplace=True)
new_df

/tmp/ipykernel_40392/4219641197.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.drop(columns=columns_to_drop, inplace=True)

,id,about,Label,merged
0,5b133284a6da98dccdde5f03,""" High quality and perfection are the result o...",0,"[ Lujo, Calzado, diseno, Diseño, lujo, Mod..."
1,556d34fd7369641226dab000,"""BEST HAM IN THE WORLD""​- IFFA International F...",0,"[ Best ham of the world, best ham of the wor..."
2,5e57ea61d5bd4a000176bd7c,"""El mundo necesita gente como La Aguacatera, q...",0,"[Avocados, avocados]"
3,5e581dba9064ba0001ceb925,"""El valor del trabajo bien hecho""​\n\nSomos un...",0,"[Asset Management, analisis fundamental, Ges..."
4,5e55a840831f070001de01d2,"""Fabricación y distribución de complementos al...",1,"[, neuro health, silicium g7 silicium, sili..."
...,...,...,...,...
2907,5a9cf7f2a6da98d97e72e434,"𝗧𝗨𝗥𝗢𝗠𝗔𝗦 𝘀𝗶𝗻𝗰𝗲 1985, 𝘄𝗼𝗿𝗹𝗱𝘄𝗶𝗱𝗲 𝗿𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗶𝗻 𝘁𝗵𝗲...",0,"[Taylor made solutions projects, smart glass..."
2908,5eda358292a7d400014cdbb9,𝙄𝘾𝙂 𝙂𝙧𝙤𝙪𝙥 es un grupo multinacional que fabric...,0,[]
2909,614168ce66c01d0001074e07,CÓMO TE AYUDAMOS\n\n PASOS\n Definición de la...,0,[]
2910,54a1205e69702d84c5183602,What do we do?\nWe develop SaaS solutions to ...,0,"[ napalo, internet, e-commerce, ondemdeliver..."
2911,5da4df7af22f0400010d034c,Ambar Lab is your one-stop clinical laborator...,0,"[ clinical laboratory, Projects acceleration..."

### 1.12 Changing list into string for **merged**, concatinating **merged** with **about**.
This will add more crucial words to the text we will use for binary classification.
Dropping 'merged' column

In [16]:
new_df['merged'] = new_df['merged'].apply(lambda x: ' '.join(x))
new_df['about'] = new_df['about']  + new_df['merged']
new_df.drop(columns=['merged'], inplace=True)
new_df

/tmp/ipykernel_40392/4087444921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['merged'] = new_df['merged'].apply(lambda x: ' '.join(x))
/tmp/ipykernel_40392/4087444921.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['about'] = new_df['about']  + new_df['merged']
/tmp/ipykernel_40392/4087444921.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.drop(columns=['merged'], inplace=True)

,id,about,Label
0,5b133284a6da98dccdde5f03,""" High quality and perfection are the result o...",0
1,556d34fd7369641226dab000,"""BEST HAM IN THE WORLD""​- IFFA International F...",0
2,5e57ea61d5bd4a000176bd7c,"""El mundo necesita gente como La Aguacatera, q...",0
3,5e581dba9064ba0001ceb925,"""El valor del trabajo bien hecho""​\n\nSomos un...",0
4,5e55a840831f070001de01d2,"""Fabricación y distribución de complementos al...",1
...,...,...,...
2907,5a9cf7f2a6da98d97e72e434,"𝗧𝗨𝗥𝗢𝗠𝗔𝗦 𝘀𝗶𝗻𝗰𝗲 1985, 𝘄𝗼𝗿𝗹𝗱𝘄𝗶𝗱𝗲 𝗿𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗶𝗻 𝘁𝗵𝗲...",0
2908,5eda358292a7d400014cdbb9,𝙄𝘾𝙂 𝙂𝙧𝙤𝙪𝙥 es un grupo multinacional que fabric...,0
2909,614168ce66c01d0001074e07,CÓMO TE AYUDAMOS\n\n PASOS\n Definición de la...,0
2910,54a1205e69702d84c5183602,What do we do?\nWe develop SaaS solutions to ...,0
2911,5da4df7af22f0400010d034c,Ambar Lab is your one-stop clinical laborator...,0

### 1.13 Renaming columns, for simplicity

In [17]:
new_df.rename(columns={'Label': 'label'}, inplace=True)
new_df.rename(columns={'about': 'text'}, inplace=True)

new_df

/tmp/ipykernel_40392/2585862434.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.rename(columns={'Label': 'label'}, inplace=True)
/tmp/ipykernel_40392/2585862434.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.rename(columns={'about': 'text'}, inplace=True)

,id,text,label
0,5b133284a6da98dccdde5f03,""" High quality and perfection are the result o...",0
1,556d34fd7369641226dab000,"""BEST HAM IN THE WORLD""​- IFFA International F...",0
2,5e57ea61d5bd4a000176bd7c,"""El mundo necesita gente como La Aguacatera, q...",0
3,5e581dba9064ba0001ceb925,"""El valor del trabajo bien hecho""​\n\nSomos un...",0
4,5e55a840831f070001de01d2,"""Fabricación y distribución de complementos al...",1
...,...,...,...
2907,5a9cf7f2a6da98d97e72e434,"𝗧𝗨𝗥𝗢𝗠𝗔𝗦 𝘀𝗶𝗻𝗰𝗲 1985, 𝘄𝗼𝗿𝗹𝗱𝘄𝗶𝗱𝗲 𝗿𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗶𝗻 𝘁𝗵𝗲...",0
2908,5eda358292a7d400014cdbb9,𝙄𝘾𝙂 𝙂𝙧𝙤𝙪𝙥 es un grupo multinacional que fabric...,0
2909,614168ce66c01d0001074e07,CÓMO TE AYUDAMOS\n\n PASOS\n Definición de la...,0
2910,54a1205e69702d84c5183602,What do we do?\nWe develop SaaS solutions to ...,0
2911,5da4df7af22f0400010d034c,Ambar Lab is your one-stop clinical laborator...,0

### 1.14 Removing **\n** from text

In [18]:
# new_df['text'] = new_df['text'].str.replace("\n", '')
# new_df

### 1.15 Remove duplicates

In [19]:
new_df = new_df.drop_duplicates()
new_df

,id,text,label
0,5b133284a6da98dccdde5f03,""" High quality and perfection are the result o...",0
1,556d34fd7369641226dab000,"""BEST HAM IN THE WORLD""​- IFFA International F...",0
2,5e57ea61d5bd4a000176bd7c,"""El mundo necesita gente como La Aguacatera, q...",0
3,5e581dba9064ba0001ceb925,"""El valor del trabajo bien hecho""​\n\nSomos un...",0
4,5e55a840831f070001de01d2,"""Fabricación y distribución de complementos al...",1
...,...,...,...
2907,5a9cf7f2a6da98d97e72e434,"𝗧𝗨𝗥𝗢𝗠𝗔𝗦 𝘀𝗶𝗻𝗰𝗲 1985, 𝘄𝗼𝗿𝗹𝗱𝘄𝗶𝗱𝗲 𝗿𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗶𝗻 𝘁𝗵𝗲...",0
2908,5eda358292a7d400014cdbb9,𝙄𝘾𝙂 𝙂𝙧𝙤𝙪𝙥 es un grupo multinacional que fabric...,0
2909,614168ce66c01d0001074e07,CÓMO TE AYUDAMOS\n\n PASOS\n Definición de la...,0
2910,54a1205e69702d84c5183602,What do we do?\nWe develop SaaS solutions to ...,0
2911,5da4df7af22f0400010d034c,Ambar Lab is your one-stop clinical laborator...,0

### 1.16 Saving cleaned data

In [20]:
new_df.to_csv('../../data/processed/clean.csv', index=False)